name: ci-nodejs
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  buid:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Nodejs 
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm ci
      - name: Buid TypeScript
        run: npm run build
      - name: Login to DockerHub
        uses: docker/login-action@v3 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/ci-cd-vps:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/ci-cd-vps:${{ github.run_number }}
      - name: Done
        run: echo "Docker Image pushed successfully!"      